export enum EProductType {
  RETAIL = "RETAIL",
  HANDCRAFTED = "HANDCRAFTED",
  COMMODITY = "COMMODITY",
  LUXURY = "LUXURY",
  CONVENIENCE = "CONVENIENCE",
  SPECIALTY = "SPECIALTY",
  NICHE = "NICHE",
  GENERIC = "GENERIC",
  DURABLE = "DURABLE",
  CONSUMABLE = "CONSUMABLE",
  DIGITAL = "DIGITAL",
}
